# Generated by Django 5.0.6 on 2024-07-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
